### ISSUE TITLE
Implement catchable errors for waveform generation

### ISSUE THREAD

**Issue by CChapmanbird** [BlackHolePerturbationToolkit/FastEMRIWaveforms#36]
Currently, many potential errors during waveform generation are invoked by the GSL error handler, which forcefully interrupts execution ignoring `try... catch` handling. 

This should instead be catchable by the user, who may then supply contingencies for these situations. Additionally some default contingencies may be added where appropriate, for instance if `max_init_len` needs to be increased this may be performed by default and re-run.

**Comment by mikekatz04** [comment]
I have implemented a first pass at this. The error catcher is in the function with brent.c since that seems to throw errors often. It should now catch errors and return a `SystemError` in Python. 

If you want errors to be caught elsewhere, let me know and I will add it. I am going to update the trajectory codes, so I am not going to mess with them now. 

Do you ever see GPU errors with this?

I am going to close this for now. Reopen if you want specific things added or if you need GPU errors caught or if this is not fixed entirely.

**Comment by CChapmanbird** [comment]
This sounds great. If you get the chance, it could be good to catch errors in `ellint.c` as well, as this often throws `too many iterations` errors when `p0` is low for Kerr prograde inspirals.

I don't tend to see GPU errors, personally, except out of memory errors sometimes which are already catchable. 

I'll give you some feedback when the changes are on the main branch and I get the chance to try them with some problematic code.

**Comment by mikekatz04** [comment]
I added this functionality. I did quick tests and it seemed fine but I did not know specific parameters that throw errors. So, it should work, but if it does not work, let me know.
